# Generated by Django 5.0.6 on 2024-05-19 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateField(auto_now_add=True, null=True)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='input_images/')),
                ('tb_status', models.CharField(blank=True, choices=[('Infected', 'Infected'), ('Not Infected', 'Not Infected')], max_length=100, null=True)),
                ('output_image_mask', models.ImageField(blank=True, null=True, upload_to='output_image_masks/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tb_detections', to='patient.patient')),
            ],
        ),
    ]
